In [122]:
from sklearn.datasets import load_iris

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
x,y = load_iris(return_X_y=True)

In [125]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=30)

In [126]:
from sklearn.naive_bayes import GaussianNB

In [127]:
gnb = GaussianNB()
gnb.fit(xtrain,ytrain)

GaussianNB()

In [128]:
ypred = gnb.predict(xtest)

In [129]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
print(accuracy_score(ytest,ypred))

# Always use ytest and ypred

[[13  0  0]
 [ 0 12  1]
 [ 0  1 18]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.92      0.92      0.92        13
           2       0.95      0.95      0.95        19

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

0.9555555555555556


Using Tips

In [130]:
#Dataset (Tips Dataset)
import seaborn as sns 
df  = sns.load_dataset("tips")

In [131]:
x = df[['tip', 'sex', 'smoker', 'day', 'time']]
y = df["size"]


In [132]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=10,test_size=0.25)

In [133]:
from sklearn.preprocessing import LabelEncoder

In [134]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [135]:
xtrain["sex"] = le1.fit_transform(xtrain["sex"])
xtrain["smoker"]= le2.fit_transform(xtrain["smoker"])
xtrain["time"] = le3.fit_transform(xtrain["time"])

In [136]:
xtest["sex"] = le1.transform(xtest["sex"])
xtest["smoker"]= le2.transform(xtest["smoker"])
xtest["time"] = le3.transform(xtest["time"])

In [137]:
## ONEHOT ENCODING
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [138]:
ct = ColumnTransformer(transformers=[("onehot",OneHotEncoder(drop="first"),[3])],remainder="passthrough")


In [139]:
import sys
import numpy 
numpy.set_printoptions(threshold=sys.maxsize)
xtrain = ct.fit_transform(xtrain)
xtest = ct.transform(xtest)

In [140]:
import pandas as pd
pd.DataFrame(xtrain).head()


0    1    2     3    4    5    6
0  1.0  0.0  0.0  1.76  1.0  1.0  0.0
1  0.0  1.0  0.0  1.66  1.0  0.0  0.0
2  0.0  1.0  0.0  3.50  1.0  0.0  0.0
3  1.0  0.0  0.0  2.01  1.0  0.0  0.0
4  0.0  1.0  0.0  3.00  1.0  1.0  0.0

In [141]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [142]:
gnb.fit(xtrain,ytrain)

GaussianNB()

In [143]:
ypred = gnb.predict(xtest)

In [144]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))
print(accuracy_score(ytest,ypred))

# Always use ytest and ypred

[[ 1  0  0  0  0  0]
 [10  4  3  0  5 17]
 [ 1  0  3  0  3  2]
 [ 1  2  2  0  0  5]
 [ 0  1  0  0  0  1]
 [ 0  0  0  0  0  0]]
              precision    recall  f1-score   support

           1       0.08      1.00      0.14         1
           2       0.57      0.10      0.17        39
           3       0.38      0.33      0.35         9
           4       0.00      0.00      0.00        10
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         0

    accuracy                           0.13        61
   macro avg       0.17      0.24      0.11        61
weighted avg       0.42      0.13      0.17        61

0.13114754098360656


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\ProgramData\anaconda3\Lib\site-packages\sklea